In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder

from sklearn.model_selection import train_test_split

from sklearn.linear_model import LogisticRegression

from sklearn.ensemble import RandomForestClassifier

from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

import joblib

In [4]:
df

,Name,Company,Industry,Region,Company Size,Traffic Source,Site Visits,Session Duration,Emails Opened,Demo Requested,Days Since First Interaction,Converted,Engagement Score,Source Impact Score
0,Laura Williams,"Thornton, Young and Davenport",Education,East,Small,Email,37,9.22,18,0,174,1,0.632598,0.644778
1,Sergio Hartman,Braun PLC,IT,South,Small,Webinar,7,20.58,7,0,182,0,0.325670,0.642108
2,Aaron Taylor,"Matthews, Weaver and Zavala",Healthcare,North,Medium,Ads,28,15.48,14,1,364,1,0.562804,0.641592
3,Tara Jones,Wright LLC,Finance,West,Large,Ads,7,19.43,19,1,216,0,0.438024,0.641592
4,Jamie Conley,"Daugherty, Ramsey and Lindsey",Education,North,Medium,Email,3,14.52,20,0,207,0,0.356115,0.644778
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,Joseph Martinez,Mckenzie Group,Finance,North,Medium,Organic,39,12.08,1,0,110,0,0.506886,0.634098
29996,Kathryn Allen,Stephens and Sons,Retail,South,Large,Email,28,4.26,6,0,138,1,0.363778,0.644778
29997,Laura Herrera,White Inc,Healthcare,North,Medium,Ads,18,6.43,10,1,109,1,0.324117,0.641592
29998,Madeline Le,"Huang, Johnson and Hall",Healthcare,North,Large,Ads,12,19.09,1,1,85,1,0.299886,0.641592
29999,Sarah Moore,"Hernandez, Herring and Kennedy",Retail,East,Medium,Organic,20,10.74,0,0,318,1,0.285907,0.634098

In [3]:
df = pd.read_csv("processed_lead_data.csv")

df.head()

,Name,Company,Industry,Region,Company Size,Traffic Source,Site Visits,Session Duration,Emails Opened,Demo Requested,Days Since First Interaction,Converted,Engagement Score,Source Impact Score
0,Laura Williams,"Thornton, Young and Davenport",Education,East,Small,Email,37,9.22,18,0,174,1,0.632598,0.644778
1,Sergio Hartman,Braun PLC,IT,South,Small,Webinar,7,20.58,7,0,182,0,0.325670,0.642108
2,Aaron Taylor,"Matthews, Weaver and Zavala",Healthcare,North,Medium,Ads,28,15.48,14,1,364,1,0.562804,0.641592
3,Tara Jones,Wright LLC,Finance,West,Large,Ads,7,19.43,19,1,216,0,0.438024,0.641592
4,Jamie Conley,"Daugherty, Ramsey and Lindsey",Education,North,Medium,Email,3,14.52,20,0,207,0,0.356115,0.644778

In [4]:
df['Industry'].unique()

array(['Education', 'IT', 'Healthcare', 'Finance', 'Retail'], dtype=object)

In [5]:
df['Traffic Source'].unique()

array(['Email', 'Webinar', 'Ads', 'Organic'], dtype=object)

# Remove Column

In [5]:
X = df.drop(
    ['Converted', 'Name', 'Company'],
    axis=1
)

y = df['Converted']

# Encode Categorical Data

In [6]:
encoders = {}

for col in X.select_dtypes(include='object').columns:

    le = LabelEncoder()

    X[col] = le.fit_transform(X[col])

    encoders[col] = le

In [8]:
X

,Industry,Region,Company Size,Traffic Source,Site Visits,Session Duration,Emails Opened,Demo Requested,Days Since First Interaction,Engagement Score,Source Impact Score
0,0,0,2,1,37,9.22,18,0,174,0.632598,0.644778
1,3,2,2,3,7,20.58,7,0,182,0.325670,0.642108
2,2,1,1,0,28,15.48,14,1,364,0.562804,0.641592
3,1,3,0,0,7,19.43,19,1,216,0.438024,0.641592
4,0,1,1,1,3,14.52,20,0,207,0.356115,0.644778
...,...,...,...,...,...,...,...,...,...,...,...
29995,1,1,1,2,39,12.08,1,0,110,0.506886,0.634098
29996,4,2,0,1,28,4.26,6,0,138,0.363778,0.644778
29997,2,1,1,0,18,6.43,10,1,109,0.324117,0.641592
29998,2,1,0,0,12,19.09,1,1,85,0.299886,0.641592
29999,4,0,1,2,20,10.74,0,0,318,0.285907,0.634098

In [7]:
df['Industry'].unique()

array(['Education', 'IT', 'Healthcare', 'Finance', 'Retail'], dtype=object)

In [10]:
print(X.columns)

Index(['Industry', 'Region', 'Company Size', 'Traffic Source', 'Site Visits',
       'Session Duration', 'Emails Opened', 'Demo Requested',
       'Days Since First Interaction', 'Engagement Score',
       'Source Impact Score'],
      dtype='object')

# SAVE ENCODERS

In [8]:
joblib.dump(
    encoders,
    "encoders.pkl"
)

['encoders.pkl']

# Train Test Split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Train Logistic Regression

In [10]:
lr = LogisticRegression()

lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

C:\Users\tejas\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

# Evaluate Logistic Regression

In [11]:
print("LOGISTIC REGRESSION")

print(
    "Precision:",
    precision_score(y_test, y_pred_lr)
)

print(
    "Recall:",
    recall_score(y_test, y_pred_lr)
)

print(
    "F1 Score:",
    f1_score(y_test, y_pred_lr)
)

print(
    "ROC AUC:",
    roc_auc_score(y_test, y_pred_lr)
)

LOGISTIC REGRESSION
Precision: 0.6865105908584169
Recall: 0.800780234070221
F1 Score: 0.7392557022809124
ROC AUC: 0.5741720195873147

# Train Random Forest

In [12]:
rf = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

# Evaluate Random Forest

In [13]:
print("RANDOM FOREST")

print(
    "Precision:",
    precision_score(y_test, y_pred_rf)
)

print(
    "Recall:",
    recall_score(y_test, y_pred_rf)
)

print(
    "F1 Score:",
    f1_score(y_test, y_pred_rf)
)

print(
    "ROC AUC:",
    roc_auc_score(y_test, y_pred_rf)
)

RANDOM FOREST
Precision: 0.739685124864278
Recall: 0.7087126137841352
F1 Score: 0.7238677115154735
ROC AUC: 0.6318505064280305

# Train XGBoost

In [14]:
xgb = XGBClassifier(
    eval_metric='logloss'
)

xgb.fit(X_train, y_train)

y_pred_xgb = xgb.predict(X_test)

# Evaluate XGBoost

In [15]:
print("XGBOOST")

print(
    "Precision:",
    precision_score(y_test, y_pred_xgb)
)

print(
    "Recall:",
    recall_score(y_test, y_pred_xgb)
)

print(
    "F1 Score:",
    f1_score(y_test, y_pred_xgb)
)

print(
    "ROC AUC:",
    roc_auc_score(y_test, y_pred_xgb)
)

XGBOOST
Precision: 0.7368282402528978
Recall: 0.7274382314694409
F1 Score: 0.7321031278628451
ROC AUC: 0.6319325728112866

# Hyperparameter Tuning using GridSearchCV

In [16]:
from sklearn.model_selection import GridSearchCV

In [17]:
params = {

    'n_estimators': [50, 100],

    'max_depth': [5, 10]

}

In [18]:
grid = GridSearchCV(

    RandomForestClassifier(),

    param_grid=params,

    cv=3,

    scoring='f1',

    verbose=2

)

# TRAIN GRIDSEARCH

In [21]:
grid.fit(X_train, y_train)

Fitting 3 folds for each of 4 candidates, totalling 12 fits
[CV] END .......................max_depth=5, n_estimators=50; total time=   0.6s
[CV] END .......................max_depth=5, n_estimators=50; total time=   0.5s
[CV] END .......................max_depth=5, n_estimators=50; total time=   0.5s
[CV] END ......................max_depth=5, n_estimators=100; total time=   1.2s
[CV] END ......................max_depth=5, n_estimators=100; total time=   1.0s
[CV] END ......................max_depth=5, n_estimators=100; total time=   1.0s
[CV] END ......................max_depth=10, n_estimators=50; total time=   0.9s
[CV] END ......................max_depth=10, n_estimators=50; total time=   1.0s
[CV] END ......................max_depth=10, n_estimators=50; total time=   1.0s
[CV] END .....................max_depth=10, n_estimators=100; total time=   2.2s
[CV] END .....................max_depth=10, n_estimators=100; total time=   2.0s
[CV] END .....................max_depth=10, n_estimators=100; total time=   2.0s

GridSearchCV(cv=3, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [5, 10], 'n_estimators': [50, 100]},
             scoring='f1', verbose=2)

# BEST PARAMETERS

In [22]:
print(grid.best_params_)

{'max_depth': 5, 'n_estimators': 100}

# BEST MODEL

In [23]:
best_model = grid.best_estimator_

# FINAL PREDICTION

In [24]:
y_pred = best_model.predict(X_test)

# FINAL ACCURACY

In [25]:
print(
    "Accuracy:",
    accuracy_score(y_test, y_pred)
)

Accuracy: 0.6398333333333334

# Load Saved Model

In [26]:
joblib.dump(
    best_model,
    "lead_scoring_model.pkl"
)

['lead_scoring_model.pkl']

In [27]:
print(X.columns)

Index(['Industry', 'Region', 'Company Size', 'Traffic Source', 'Site Visits',
       'Session Duration', 'Emails Opened', 'Demo Requested',
       'Days Since First Interaction', 'Engagement Score',
       'Source Impact Score'],
      dtype='object')

# Predict New Lead

In [53]:
new_data = [[
    1,   # Industry
    2,   # Region
    1,   # Company Size
    3,   # Traffic Source
    10,  # Site Visits
    15,  # Session Duration
    5,   # Emails Opened
    1,   # Demo Requested
    20,  # Days Since First Interaction
    30,  # Engagement_Score
    0.45 # Source_Impact_Score
]]

In [54]:
new_data = pd.DataFrame([{
    'Name': 1,
    'Company': 1,
    'Industry': 1,
    'Region': 2,
    'Company Size': 1,
    'Traffic Source': 3,
    'Site Visits': 10,
    'Session Duration': 15,
    'Emails Opened': 5,
    'Demo Requested': 1,
    'Days Since First Interaction': 20,
    'Engagement Score': 30,
    'Source Impact Score': 0.45
}])

# Scale data
new_data_scaled = scaler.transform(new_data)

# Prediction
prediction = model.predict(new_data_scaled)

print(prediction)

[1]

In [55]:
print(X.columns.tolist())

['Name', 'Company', 'Industry', 'Region', 'Company Size', 'Traffic Source', 'Site Visits', 'Session Duration', 'Emails Opened', 'Demo Requested', 'Days Since First Interaction', 'Engagement Score', 'Source Impact Score']